### ISSUE TITLE
Improvement: Build with LTS version of Node and AppVeyor

### ISSUE THREAD

**Issue by hypery2k** [as-ideas/oil#115]
The current travis configuration uses Node 7 to build. It would be better to stick to Node 8 or the upcoming NodeLTS version, see here for [more](https://blog.holisticon.de/2018/03/ready-for-nodejs-8/).
Node 8 also improves overall install performance an dev machine. Maybe it would be also a good idea to test several NodeJS version, like [here](https://github.com/hypery2k/galenframework-cli/blob/develop/.travis.yml#L7).
Besides that a ci build on AppVeyor would also ensure that the setup works on Windows machines.

I could sent a PR for these both issue.

**Comment by subsend** [comment]
Hey, thanks for Idea! https://github.com/as-ideas/oil/commit/384575c14a86c4941eadadd5b41eacef3d8c44ed

**Comment by CanardSauvage** [comment]
@subsend upgraded to a newer node version with his commit (he forgot the PR and to mention the issue in the commit ;) )

AppVeyor may be a good idea, for testing windows, as I have a Windows machine at home ;) @hypery2k feel free to create a PR for the pull request

As for multiple node versions - what would be the benefit?

**Comment by hypery2k** [comment]
the multiple node version would just help in case for development. Sometimes dependencies and build stuff works differently in different version, so for a library on the use side no big issue
