### ISSUE TITLE
Is there a way to hide irrelevant third parties?

### ISSUE THREAD

**Issue by TimothyDigitalOyster** [as-ideas/oil#126]
I was assuming that IabWhitelist would hide any providers not whitelisted but it doesn't appear to work... 

I have these as my settings for testing but it's refusing to hide anything not in the array...

`  "iabVendorListUrl" : "https://service.cmp.oath.com/cmp/v0/vendor_list/global",
  "iabVendorWhitelist" : [42,164],`

**Comment by phogel** [comment]
The documentation for `iabVendorWhitelist` and `iabVendorWhitelist` is a bit unclear at this point. Their effect really is that in the response to `__cmp.getVendorConsents()` the consent values for the given excluded vendors are always false. It would make sense to hide excluded vendors from the advanced settings view.
You could in the mean time create your own vendor list with the standard 5 and only those two you're trying to show?

**Comment by TimothyDigitalOyster** [comment]
Cool, Thank you :)
