### ISSUE TITLE
POI?

### ISSUE THREAD

**Issue by TimothyDigitalOyster** [as-ideas/oil#128]
Been trying to work out how this works.
Documentation is sparse.

I have two pages on different domains is it possible to generate consent for both pages using this?

e.g.
    abc.com/index.html 
First pages leads to 
    xyz.com/index.html

Is it possible to get consent from the first page with the second pages listed on it so that the second page doesn't additionally require a permission...

**Comment by phogel** [comment]
Yes, you can store a user's consent across different domains:
- Upload [hub.html](https://github.com/as-ideas/oil/blob/master/release/1.1.2/hub.html) to one of your servers
- Add all required parameters for POI to your configuration. Details about them [in the docs](http://oil.axelspringer.com/docs/#poi-configuration) (all relevant parameters start with `poi_`)
- Use the same POI settings on different domains

**Comment by TimothyDigitalOyster** [comment]
Where do I change the names of the "companies" within the group?

**Comment by phogel** [comment]
Adding to the above: You want to upload not only `hub.html` but also `hub.js`.

These are available labels [http://oil.axelspringer.com/docs/#label-configuration-parameters](http://oil.axelspringer.com/docs/#label-configuration-parameters)
I think you're looking for the label `label_poi_group_list_heading`?

**Comment by TimothyDigitalOyster** [comment]
There are two different settings related to POI.. 
      "label_poi_group_list_heading" : "Your consent for sites related to this site",
      "label_poi_group_list_text" : "Here is a list of related sites:",

Which generates something like: 

Your consent for sites related to this site
Here is a list of related sites:
*************
*************

What I was after is where to modify the sections that are ***'d out..

**Comment by CanardSauvage** [comment]
You need any domain, where the central cookie is stored. For example any.domain.com. 
On this domain you need the hub.html from the release folder (in the released versions, the hub.js is inlined in the hub.html)

You need to configure this setup:
“poi_activate_poi”: true
"poi_hub_origin": "//any.domain.com"
"poi_hub_path": "/hub.html",
"poi_group_name": "MyGroupName"

The group name is kind of a prefix - you can have multiple groups on the same domain. The cookie is shared per group

For the group you will legally need to list all websites/companies belonging to it. We call this the poi-list and you can add a JSON file. --> In the release folders (1.1.2) the is a folder name poi-list and you can add a json-file with the name of your poi_group_name

You can have all the files from one release in one folder and configure it accordingly, look at oil.axelspringer.com/demos/open-source-example.html

**Comment by phogel** [comment]
There's section in the Readme now on this matter https://github.com/as-ideas/oil#poi-and-soi
#132
