### ISSUE TITLE
Improve event-handling for analytics

### ISSUE THREAD

**Issue by Waschnick** [as-ideas/oil#141]
* Collect all oil.js events in a queue, so when the tracking tool is not loaded yet the events aren't lost
* Add a description how to create reports for oil.js with Google Analytics
* Detailed documentation

**Comment by sschenke** [comment]
See https://github.com/as-ideas/oil/pull/148/

**Comment by CanardSauvage** [comment]
Merged! What about documentation about how to create reports wie GA?

**Comment by Waschnick** [comment]
Closed - documentation can be found here https://oil.axelspringer.com/release/1.2.5/docs/index.html#tracking-and-google-analytics-events

I would like to have some Screenshots with example dashboards, but good enough for now.
