### ISSUE TITLE
Promises and Internet Explorer

### ISSUE THREAD

**Issue by kleins** [as-ideas/oil#146]
Hi there - 

what about Internet Explorer Support? 

Internet Explorer always prints this line to console: 

`Unhandled promise rejection TypeError: Das Objekt unterstützt die Eigenschaft oder Methode “assign” nicht`

MDN shows no Support for any Internet Explorer Version. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

Is there a workaround or something like that? 

Thanks in advanced. 

Sascha

**Comment by phogel** [comment]
Hey thanks for asking. Working on it right now. Will let you know when the fix is up👍

**Comment by kleins** [comment]
Thanks for the reply. What will be your solution? I've read something about Polyfill which should help to solve this Problem. Polyfill was also available in version 1.1.0. But with Polyfill we had some problems on some sites which also implemented Polyfill. 

Thanks

**Comment by phogel** [comment]
We removed the babel-polyfill because it interfered with some of our sites, too. That's why we removed it. Promise is polyfilled but the new error you're seeing is from inside the ConsentString library – Object.assign is used but not polyfilled.
Now we're going to load the polyfills dependent on whether the browser provides them natively or not. You can view my current implementation state here: https://github.com/as-ideas/oil/blob/oil-190-browserstacks/src/polyfill.js

**Comment by phogel** [comment]
The fix has been merged with #150

**Comment by kleins** [comment]
thank you for your reply. 
I've checkt the merge and sadly it didn't work as expected. In IE 9 I get a similar error (see Screenshot), but consent layer is displayed as expected. 

In IE 10 __cmp callback function would not called: 

<pre>__cmp('getVendorConsents', null, function (result) {
    // The callback is never called
    my_lib.consent_given = true;
});</pre>

So consent wouldn't given. 

This behaviour also happen in IE 9. 

IE 11, seems to work as expected. Consent the callback is called and consent is given
<img width="913" alt="dashboard 2018-06-25 14-51-05" src="https://user-images.githubusercontent.com/2216195/41855778-b7e29796-7893-11e8-840c-178287b96e0a.png">

**Comment by phogel** [comment]
The fill method is polyfilled will be polyfilled in the next release. See this PR #154 
Will write a seperate test for `getVendorConsents` on IE10

**Comment by CanardSauvage** [comment]
With Version 1.2.1 there should be no issues.
