### ISSUE TITLE
Mobil view is hiding the last thirdparty 

### ISSUE THREAD

**Issue by SindreSvendby** [as-ideas/oil#161]
#### Problem
The "OK" button is hidding the last thirdparty in the  mobil view 

#### Example site
https://oil.axelspringer.com/demos/open-source-example.html 

#### Screenshot

On mobile
![image](https://user-images.githubusercontent.com/1047421/42210500-72f2c4ca-7eb1-11e8-82b4-27ffe720a8db.png)

On desktop
![image](https://user-images.githubusercontent.com/1047421/42210530-86072f06-7eb1-11e8-9b17-033a1ea1836a.png)

#### Expected result

You can see the last thirdpary in the list on mobil (in the example page this is  `mainADV Srl`)

**Comment by phogel** [comment]
Fixed with #165
