### ISSUE TITLE
General Questionnaire  Quickstart - ENGLISH

### ISSUE THREAD

**Issue by DanielPastorPeno** [as-ideas/oil#188]
In my Company we want to track again Users Data, of course compatible with GDPR. We founded Oil.js the best option for our Enterprise. 
Despite that the Documentation was so clearly, we have some question:

**1.- Is Oil.js compatible with Wordpress?**
We use the famous Third Party Vendor Wordpress for our Website, we have the question if there is problems with PublicPath, Local_url, or Locale when we use it in Wordpress
**2.- Oil.js doesn’t blocked automatically the Data Tracking. How could we do that?**
For the moment, we added this term in our Website:
window['ga-disable-UA-XXXXXX-Y'] = true;
That was a Google Analytics requirement; I ask if with Oil.js the need this term more or we can remove it. If we remove it, are we completely conform with GDPR? I’m worry because Axel Springer says:
“OIL creates a standard for the Opt-In but can’t automatically stop your site from tracking your users. So to actually make your page respond to opt-ins you also need to do the following:
Make sure your page doesn’t track the user in its default state.”
Is so then the Soft Blocking of DOM sufficient for block automatically the Data Tracking?
**3.- Get Vendors Consent**
If we do not change the Integrate OIL code (that we can find in the documentation as Integrate Oil, the Second Step in the Quickstart) should we add the getVendorConsents Code too?
The same for getConsentData and getPublisherConsents. 
**4.- How works the Data Delivery Process?**
First of all, How track Axel Springer our Data? And so importante your us to know how send Axel Springer these Data to Google Analytics?
I’m worry if we can lose some Data in this process. Shoul I understand that every work automatically with this term?
} if (window.ga && window.ga.loaded && event && event.data && eventDataContains('oil_optin_done')) { // event name
var nonInteraction = true; // should be set to false for non-click events
window.ga('send', 'event', 'OIL', 'oil_optin_done', {'nonInteraction': nonInteraction}); }
Thank you so much your our time and our attention
Kind regards
Daniel Pastor

**Comment by phogel** [comment]
Hi Daniel, would you be able to rephrase this request in English? Because I think your questions are of interest to our international audience, too, and my response will be useful for everyone then. Thanks

**Comment by DanielPastorPeno** [comment]
I have already did
