### ISSUE TITLE
label_cpc_purpose_0x_text/desc from locale.json is being ignored

### ISSUE THREAD

**Issue by Ratcreamsoup** [as-ideas/oil#193]
When declaring localized values for label_cpc_purpose_0[1-7]_text and label_cpc_purpose_0[1-7]_desc, the English language defaults are still rendered instead.

**Comment by ptc** [comment]
did you add those values into your locale.json or within the embedded configuration?

**Comment by Ratcreamsoup** [comment]
It's really a duplicate of #192, so I'll close this issue here.
