### ISSUE TITLE
third-party view: Expanding a party shows undefined/undefined

### ISSUE THREAD

**Issue by Ratcreamsoup** [as-ideas/oil#194]
The navigating to the third-party view (click on as-js-thirdPartyList), the elements of that list can be expanded by clicking on the + symbol, which simply shows "undefined" twice under the chosen entry.

**Comment by Ratcreamsoup** [comment]
It doesn't work in the sandbox either. Just open http://sandbox.oiljs.org/ in Chrome or Firefox, click on "trusted partners" and then click on the +-character to the left of any of the vendors listed there, for example Exponential Interactive, Inc, Captivity Technologies Limited or affilinet. Each just shows "undefined" twice - once for the description text and below for the third party link.

**Comment by ptc** [comment]
Now I got it.
