### ISSUE TITLE
hub.1.2.2-SNAPSHOT.min.js is searched in DocumentRoot instead of publicPath

### ISSUE THREAD

**Issue by Ratcreamsoup** [as-ideas/oil#195]
As I have discovered some localization bugs in release 1.2.1, I tried it with the current snapshot. I have set 
"publicPath": "//my.host.tld/1.2.2-SNAPSHOT/",
"poi_activate_poi": true,
"poi_hub_origin": "//my.host.tld",
"poi_hub_path": "/1.2.2-SNAPSHOT/hub.html"

In this constellation, oil tries to fetch hub.1.2.2-SNAPSHOT.min.js from //my.host.tld/hub.1.2.2-SNAPSHOT.min.js instead of //my.host.tld//1.2.2-SNAPSHOT/hub.1.2.2-SNAPSHOT.min.js

**Comment by Ratcreamsoup** [comment]
No worries, I already fixed it in my test install - I just wanted to let you know there might be a glitch in the snapshot :relaxed:

**Comment by phogel** [comment]
great! 👍
