### ISSUE TITLE
Fill is not supported in IE

### ISSUE THREAD

**Issue by SindreSvendby** [as-ideas/oil#201]
Hi! 

In the current version of oil your are using Array.fill (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill) 

But this is no polyfill, and this method is not supported by IE. 

The result is an exception on `Line 16 : Column 13139` in the file oil.1.2.1-RELEASE.min.js

**Comment by SindreSvendby** [comment]
Well, I'm not the user. But no version of IE har support for the `fil` method. 
If you want to test it, just go to your [demo sites](https://oil.axelspringer.com/demos/) and use IE 11 trough https://browserstack.com or similar

**Comment by subsend** [comment]
Hello SindreSvendby, we have already fixed this issue, see: https://github.com/as-ideas/oil/commit/dc076a64eddae612ed324692f1f957cb7ecbbb4c
