### ISSUE TITLE
Vendor Based Opt-Out for Users

### ISSUE THREAD

**Issue by FGoessler** [as-ideas/oil#205]
Right now it is only possible for a user to opt-in/out for the different purposes but not on a per vendor basis. 

So there is no way to say for a user: „I‘m totally fine with personalized ads, but not from company XYZ since I don‘t trust them.“
I am not a legal expert, but in my understanding GDPR (and the upcoming E-Privacy Directive) are aiming at exactly such a use case. 

Is this a feature that you considered to be activated via a config option? 
What‘s the reasoning behind not having such a feature (optionally)? 
Are there any workarounds for this done by others?

**Comment by ptc** [comment]
Hi @FGoessler, thats actually a planned feature which is already in our backlog.

**Comment by FGoessler** [comment]
Awesome - thanks for the quick response! Shall we leave this issue open until then or do you have anything to link to?

**Comment by ebauvir** [comment]
Hi, can you please provide an update as to when this feature will be released?
