### ISSUE TITLE
vendorlist is called multiple times

### ISSUE THREAD

**Issue by SindreSvendby** [as-ideas/oil#206]
It seems that there is a bug/racecondition, when you load several ads on page load. 

When a page loads one ad, and on scroll triggers a new, then we only see one request to the vendorlist.

But when we load more then one ad on page load, we see one request pr ad. 

![image](https://user-images.githubusercontent.com/1047421/45024948-727a2780-b03a-11e8-8298-8fb27df2acc7.png)
![image](https://user-images.githubusercontent.com/1047421/45025152-051ac680-b03b-11e8-85f0-57023c24d5b8.png)

This can be seen at https://www.seher.no/kjendis/ikke-min-skyld-at-ben-affleck-er-pa-rehab/70168240 on a medium size monitor.

**Comment by ptc** [comment]
We'll investigate it.
