### ISSUE TITLE
Support local storage

### ISSUE THREAD

**Issue by FGoessler** [as-ideas/oil#212]
As I see so far the users choices are stored in a cookie (`oil_data`). Also test setting are stored in cookies like `oil_preview`. From what I see so far however there's no need to store this information in a cookie but it could be stored in local storage. 

At least for the Site-Opt-In case. The benefits of using local storage opposed to a cookie is that we save bandwidth on all requests as cookie's are always added to the header of every request for its domain. Local storage support is also pretty widespread (see https://developer.mozilla.org/de/docs/Web/API/Window/localStorage) and all major browsers (even IE 8) support it for quite a while. From what I see the server is usually not interested in the cookie values either, so I see no reason to send this data to the server.

Is this something you looked in or are looking into in the near future? Could be put behind a config flag to not break existing implementations.

**Comment by FGoessler** [comment]
Hey - no information or statement about this yet?

**Comment by ltparis2018** [comment]
You're right - local storage is currently not used by OIL. The layer uses first party cookies for single opt-ins and third party cookies for power opt-ins. Surely, this could be implemented with local storage too. But this is currently not on our roadmap.
OIL uses cookies to be compliant with the IAB specifications. Furthermore, it must be guaranteed that consent information is saved for a configurable amount of time. As stated on the page behind the link you provided this is not guaranteed at least for Safari Mobile.
