### ISSUE TITLE
Clarification about CMP registration in the docs missing

### ISSUE THREAD

**Issue by Ratcreamsoup** [as-ideas/oil#213]
I'd like to have some clarification on the requirement for registration as CMP by IAB Europe: Does the registration of OIL as CMP cover any self hosted deployment of OIL or would any publisher who wants to use OIL as their IAB Europe CMP in production have to register their deployment as a new CMP with IAB Europe?

In the IAB Europe webinar it was mentioned that signals from unregistered CMPs are considered invalid, so just to make sure: If a publisher follows the docs, which at this time do not mention getting registered as CMP, would the self hosted OIL deployment pass as a valid CMP?

Kind regards

  Markus

**Comment by ltparis2018** [comment]
Hello Markus,
as long as you use OIL as provided you can host it by yourself and use our CMP id. The layer is already branded with it. Therefore, it always sends a valid CMP id. 
However, if you want to fork the project and create a customized version of OIL for your own purposes you have to register the result as CMP with IAB Europe.
Hope this helps.
Best regards,
Alex.
