### ISSUE TITLE
Specifying the parent domain to put the consent cookie on

### ISSUE THREAD

**Issue by yar** [as-ideas/oil#216]
We have a website (say, example.com) which is translated into different languages and is available as www.example.com, fr.example.com, de.example.com etc.

If I use oil.js in SOI-mode, each translated version will try to set its own consent cookie. While it is acceptable, we would prefer to have a single cookie set on the parent domain ".example.com" and covering all translations. After all, this is one organisation.

What is your view on allowing to specify the cookie domain in the oil.js configuration?

**Comment by ltparis2018** [comment]
To support this use case OIL provides the power opt-in feature. It is described in detail in our documentation. Please have a look here: https://oil.axelspringer.com/docs/#power-opt-in-poi-or-site-opt-in-soi
If you do not need single opt-in anymore you can deactivate it using the configuration key {{poi_subscriber_set_cookie}} (see https://oil.axelspringer.com/docs/#functional-configuration-parameters for details).
