### ISSUE TITLE
SNAPSHOT.min.js is huge

### ISSUE THREAD

**Issue by mxhCodes** [as-ideas/oil#218]
The oil.js framework offers a lot and is easy to use, thus I want to thank you for your contribution.

Currently I see one following design problem: It brings a lot JS overhead to the table when directly using the compiled releases. The already minified compiled SNAPSHOT.min.js of latest release 1.2.5 has a size of 76KB, which is almost the size of a minified jQuery and not proportionate to what it usually does in the end.

For what it does in the end, an estimated size of 10KB to 20KB would be reasonable. The framework already uses chunks to be dynamically loaded when needed, maybe this concept can be enlarged to reduce the size of the initially required SNAPSHOT-min.js script.

**Comment by mxhaupt** [comment]
Thank you @Waschnick for your quick response and feedback on this. Currently I have not investigated in detail yet regards what could be optimized / moved to chunks. The size allocation map could be indeed very useful.

**Comment by hypery2k** [comment]
an option would be to split up into two NPM packages: one core for dev integration and one full for runtime easy-to-use one. I also did this with my galen nom packages [here](https://github.com/hypery2k/galenframework-cli).

@Waschnick
If needed I can help on this issue
