### ISSUE TITLE
Always tries to read poi-list.json

### ISSUE THREAD

**Issue by sascha-hendel** [as-ideas/oil#222]
I configured oil.js for SOI use (poi_activate_poi: false) with advanced options enabled (advanced_settings: true).

If I click now on "more Information" button it fails with console message: XHR unable to load "https://unpkg.com/@ideasio/oil.js@1.2.5/release/current/poi-lists/default.json" (404).

This file is not existent, because I'm not using POI mode, but oil.js still try to load it and fails :(

**Comment by Waschnick** [comment]
Fixed with #227
