### ISSUE TITLE
getVendorConsents callback not called when library is still loading

### ISSUE THREAD

**Issue by torstendunkel** [as-ideas/oil#224]
Hello everybody,

first of all thank you very much for creating this project. It is really easy to implement and helps us a lot.

During implementation to our sites i think that i found a bug. 
After loading the stub and before completing the loading of the other parts ( chunks) of oil the stored callbacks are not called after loading and initializing process is done.

I reproduced this behaviour on that demo site:
https://s3-eu-west-1.amazonaws.com/media.das.tamedia.ch/testing/playground/dev/oil/test.html

I am first loading the stub
Then calling 
`
__cmp('getVendorConsents', null, (results) => {
  | console.log("Got vendor consent", results);
  | });
`

And after that i am loading the rest of the library. The defined callback is never fired.
Is this a bug or do i understand something wrong?
Thank you very much for your help
Torsten

**Comment by mindplay-dk** [comment]
Opened it in Chrome and see "Got vendor consent" and the object value in the console.

Maybe you fixed it?
