### ISSUE TITLE
Opt out confirmation doesn't work on Preference Center

### ISSUE THREAD

**Issue by stackrainbow** [as-ideas/oil#229]
If using the Oil Preference Center on a page with
```<div id="oil-preference-center"></div>```and ```window.AS_OIL.showPreferenceCenter();```
and the configuration option ```"require_optout_confirm": true,``` the following JavaScript error occurs, blocking the opt-out:
```
Uncaught (in promise) TypeError: Cannot read property 'insertBefore' of null
    at 0.1.2.5-RELEASE.chunk.js:1
    at new Promise (<anonymous>)
    at s (0.1.2.5-RELEASE.chunk.js:1)
    at HTMLInputElement.p (0.1.2.5-RELEASE.chunk.js:1)
```
It looks like this is caused by looking for a hardcoded #as-oil-cpc although I'm not too sure. As a workaround I've disabled the option on that page.

**Comment by ptc** [comment]
Thx. We'll have a look at it.

**Comment by ltparis2018** [comment]
The problem was, that CSS classes for CPC in the opt-in layer and for CPC integrated in the web page are different. But only for one of them was looked. I fixed this. We plan to add the bugfix to the next OIL release.
