### ISSUE TITLE
poi_list URL is based on publicPath, not poi_hub_origin

### ISSUE THREAD

**Issue by mgolebiowski** [as-ideas/oil#239]
When configuration contains `publicPath` and `poi_hub_origin` URL for poi_list is based on `publicPath` which is inconsistent with documentation [1]. 

### How to reproduce:
Create configuration with publicPath with different URL than hub_origin. Oil will try to fetch POI List from `__OIL_PUBLIC_PATH__ + 'poi-lists/' + groupName + '.json'`[2]

### How it should work:
POI List should be fetched from `__POI_HUB_PATH__+'poi_lists/' + groupName + '.json'`

[1] http://oil.axelspringer.com/docs/#poi-power-opt-in 
[2] https://github.com/as-ideas/oil/blob/f40467cf732311d08b1b950b9d1550b9bd3d199c/src/scripts/poi-list/poi.group.list.js#L19

**Comment by ptc** [comment]
We'll check it.

**Comment by ltparis2018** [comment]
This problem is fixed with pull request #252. The `poi-lists` directory is based on `poi_hub_origin` now (but not on `poi_hub_path` - this points to an HTML file).
We plan to add this fix to our next OIL release.
