### ISSUE TITLE
 document.body.insertBefore is called before the body is available

### ISSUE THREAD

**Issue by terhoutd** [as-ideas/oil#253]
I have placed all the oil code quite high in the head of my page.
as a result I get this error 8 times out of 10.
![image](https://user-images.githubusercontent.com/4737167/58173644-30624600-7c9c-11e9-892f-3c949546ba33.png)
Inspecting the code it comes from                 document.body.insertBefore(t, document.body.firstElementChild),

which is called by the renderoil function.

If I move the oil main js file to the bottom of the head then the errors don't happen anymore.
It appears the code expects the body to be available while there is 0 guarantee it will be.

**Comment by subsend** [comment]
Hi terhoutd,

thank you for reporting this issue. We will fix this issue in the next release. For the workaround you have to place oil.1.3.0-RELEASE.min.js after the <body> - tag.
