### ISSUE TITLE
Support for TCF v2?

### ISSUE THREAD

**Issue by hemdagem** [as-ideas/oil#269]
Are there plans to support TCF Version 2? Since its now gone from public preview to final.

**Comment by and-poulsen** [comment]
Any news on this?

**Comment by and-poulsen** [comment]
Any news on this?
@Waschnick , @ltparis2018

**Comment by trymedo** [comment]
Would love an update of some kind - TCF 2.0 is very close to being released and we're already having to look at alternatives in case Oil.js doesn't support it. The AppNexus CMP have clearly stated that they have no plans to update to 2.0 - it would be good if AS-IDEAS could let us know one way or the other 👍

**Comment by rbuer** [comment]
Unfortunately we will neither develop new features nor implement TCF 2.0.

**Comment by jsonUK** [comment]
Why?
