### ISSUE TITLE
Broken unpkg link in documentation (404)

### ISSUE THREAD

**Issue by paulgreg** [as-ideas/oil#271]
Hello, in the [« Delivery through unpkg.com » chapter](
https://oil.axelspringer.com/release/1.3.5/docs/index.html#delivery-through-unpkg-com) in the documentation, the `<script>` link is pointing to https://unpkg.com/@ideasio/oil.js@1.3.5/release/current/oil.min.js
That link respond with a 404 error, « Cannot find "/release/current/oil.min.js" in @ideasio/oil.js@1.3.5 ».

**Comment by athlan** [comment]
Issue is still present
