### ISSUE TITLE
cookie_expires_in_days causes a TypeError

### ISSUE THREAD

**Issue by paulgreg** [as-ideas/oil#272]
When the option `"cookie_expires_in_days": "10"` is added in the configuration of oil.js (version 1.3.5), clicking on the accept button causes a `TypeError: i.expires.toUTCString is not a function` in `oilOptIn` function.

**Comment by nielsnuebel** [comment]
@paulgreg this is also correct because "10" is a string and 10 is an integer you must omit the "".
