### ISSUE TITLE
SPA Integration

### ISSUE THREAD

**Issue by upandfine** [as-ideas/oil#274]
How can oil.js be meaningfully integrated into an SPA such as vuejs?

**Comment by NKjoep** [comment]
Have a look at the documentation https://oil.axelspringer.com/release/1.3.5/docs/index.html#oil-events.

There are a bunch of events your SPA can listen to, example: 

<table class="tableblock frame-all grid-all spread">
<colgroup>
<col style="width: 25%;">
<col style="width: 75%;">
</colgroup>
<thead>
<tr>
<th class="tableblock halign-left valign-top">Event name</th>
<th class="tableblock halign-left valign-top">Description</th>
</tr>
</thead>
<tbody>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">oil_optin_done</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">When a users selects opt-in.</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">oil_optin_done_button_clicked</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">When a users clicks the opt-in button.</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">oil_soi_optin_done</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">When a users selects opt-in and this is a single opt-in.</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">oil_poi_optin_done</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">When a users selects opt-in and this is a power opt-in.</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">oil_as_cpc_privacy_selected</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">When a user used the cpc and clicked opt-in.</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">oil_click_advanced_settings</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">When a users clicks the advanced settings button/link.</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">oil_click_back_to_main</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">When a user clicks the back link from the advanced settings page.</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">oil_no_cookies_allowed</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">When a users has no cookies allowed and the no cookies layer is displayed</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">oil_has_optedin</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">On every page reload, when the user has opted_in previously (OIL should be hidden)</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">oil_shown</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">When oil is shown</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">oil_hide_layer</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">When oil gets automatically hidden</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">oil_click_thirdparty_list</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">When a user clicks the third party list link</p></td>
</tr>
<tr>
<td class="tableblock halign-left valign-top"><p class="tableblock">oil_click_company_list</p></td>
<td class="tableblock halign-left valign-top"><p class="tableblock">When a user clicks the company list link</p></td>
</tr>
</tbody>
</table>
