### ISSUE TITLE
Cookie Preference Center (CPC) doesn’t reflect custom purpose choice

### ISSUE THREAD

**Issue by paulgreg** [as-ideas/oil#275]
The UI doesn’t reflect custom purpose choices

### Steps to reproduce
1/ Go to https://sandbox.oiljs.org/, add a custom purpose like 
```
{
  "config_version": 1,
  "publicPath": "oil",
  "advanced_settings": true,
  "timeout": -1,
  "locale": {
    "texts": {
      "label_cpc_purpose_01_text": "",
      "label_cpc_purpose_01_desc": "",
      "label_cpc_purpose_02_text": "",
      "label_cpc_purpose_02_desc": "",
      "label_cpc_purpose_03_text": "",
      "label_cpc_purpose_03_desc": "",
      "label_cpc_purpose_04_text": "",
      "label_cpc_purpose_04_desc": "",
      "label_cpc_purpose_05_text": "",
      "label_cpc_purpose_05_desc": ""
    }
  },
  "customPurposes": [
    {
      "id": "25",
      "name": "test",
      "description": "test"
    }
  ]
}
```
2/ Click on preview, then Ok or manage cookie and activate all purposes (including that custom purpose)
3/ Go to the Cookie Preference Center (CPC)
4/ The first 5 purposes are checked but not the custom purpose.
It’s off.

### Expected
4/ All purposes are checked, including the custom one.

Note that the `getPublisherConsents` call returns `  "customPurposeConsents":     "25": true }` which is correct. So this seems an UI issue.

**Comment by stephan-a** [comment]
I could also reproduce this behavior. Are there any plans to fix that issue? That would be really great :)

I also recognized that when a custom vendor is referencing a custom purpose via the attribute "purposeIds", the code snippets in optInSnippet and optOutSnippet are never executed, although the custom purpose was activated in the CPC and - like @paulgreg mentioned - gets returned by `getPublisherConsents`.

By the way: great work, guys 🥇
