### ISSUE TITLE
Link in Cookie banner Text sets all Texts to default value

### ISSUE THREAD

**Issue by loano** [as-ideas/oil#279]
Link in Cookie banner Text sets all Texts to the default value. 

How to reproduce?

Add the following for intro label:
"label_intro": " More infos in our `<a href="https://example.com/datenschutzerklaerung/">Datenschutzerkärung</a>`"

Result: All banner texts are set to default english text (We use cookies and other technologies The website uses cookies web beacons JavaScript and similar technologies. I agree that trusted partners generate pseudonymous user profiles for adapting the website to the user for market research and for advertising. The generated data can also be shared with third parties while the user profiles cannot be combined with personal data. Detailed information also on the right to withdraw consent can be found in the website's privacy policy.)

Expected Result:  More infos in our <a href="https://example.com/datenschutzerklaerung/">Datenschutzerkärung</a>

**Comment by ddjojo** [comment]
Please avoid " and use ' in the field:
"label_intro": " More infos in our <a href='https://example.com/datenschutzerklaerung/'>Datenschutzerkärung</a>"

**Comment by ddjojo** [comment]
Please avoid " and use ' in the field:
`"label_intro": " More infos in our <a href='https://example.com/datenschutzerklaerung/'>Datenschutzerkärung</a>"`

**Comment by ddjojo** [comment]
Missing 'l':
Datenschutzerkärung -> Datenschutzerklärung
