### ISSUE TITLE
Integration IVW / SZMnG / script.ioam.de -> iom is not defined

### ISSUE THREAD

**Issue by ddjojo** [as-ideas/oil#284]
Trying to integrate soft blocking and activating script.ioam.de (IVW / Infonline) will generate an ReferenceError in console: iom is not defined

Inside head:
`<script data-managed="as-oil" data-type="text/javascript" data-src="https://script.ioam.de/iam.js" data-purposes="3" type="as-oil" id="managedScriptTag1"></script>`

Inside body:
```
<script data-managed="as-oil" data-type="text/javascript" data-purposes="3" type="as-oil" id="managedScriptTag2">
var iam_data = {
"st":"abcxyz",
"cp":"xyzabc",
"sv":"in",
"sc":"yes"
}
iom.c(iam_data);
</script>
```

**Comment by phogel** [comment]
The `iom` object is created by that script from script.ioam.de/iam.js which loads asynchronously. Now you're executing the second block before `iom` was created, hence the ReferenceError. Make sure it is executed only after iam.js has successfully loaded and `window.iom` exists.
