### ISSUE TITLE
Opt-out and remove cookie?

### ISSUE THREAD

**Issue by haveagoodone** [as-ideas/oil#290]
Hello,
I wanted to ask if it is possible to delete the corresponding vendor cookies after an opt-out? E.g. an opt-out event which provides information about the corresponding purpose / vendor?

Best regards

Sascha

**Comment by nielsnuebel** [comment]
Hi Sascha,

nein geht nicht in der Version wir haben einen Fork gemacht und den ganzen Kram IAB raus geschmissen. [https://kcm.kicktemp.com/](https://kcm.kicktemp.com/) ich werde die Tage mal unseren Fork hier posten. 

https://github.com/as-ideas/oil/blob/master/src/scripts/core/core_cookies.js#L162

Man könnte die Config erweitern und dann müsste man pro service die gesetzten Cookies im Json haben und dann dort die Cookies löschen. Sollte aber kein Problem sein. Werden wir in unserer Version einbauen.

**Comment by alexanderknapstein** [comment]
Hey @nielsnuebel, 
ich wäre an Deinem Fork interessiert. Habt Ihr das schon mal irgendwo veröffentlicht?

Danke vorab,
LG, Alex

**Comment by nielsnuebel** [comment]
Hey @alexanderknapstein,

ich kann diesen mal wieder publishen. Wir haben eine Komplette Lösung gebaut für ein CMS.

Ich meld mich dann mit updates.

BG, Niels

**Comment by alexanderknapstein** [comment]
Hallo @nielsnuebel, das wäre cool. Danke!
