### ISSUE TITLE
Plans to support LGDP

### ISSUE THREAD

**Issue by condini-mastheus** [as-ideas/oil#298]
I know most of GDPR topics covers a lot of LGDP, but is good to know the project roadmap. 🚀

**Comment by BartVB** [comment]
Oil supports TCF 1.0 but there are no plans to implement version 2.0:
https://github.com/as-ideas/oil/issues/269#issuecomment-601268833

This means that Oil.js stops being useful after June 30, 2020:
https://iabeurope.eu/uncategorized/tcf-v2-0-switchover-qa/

**Comment by condini-mastheus** [comment]
> Oil supports TCF 1.0 but there are no plans to implement version 2.0:
> [#269 (comment)](https://github.com/as-ideas/oil/issues/269#issuecomment-601268833)
> 
> This means that Oil.js stops being useful after June 30, 2020:
> https://iabeurope.eu/uncategorized/tcf-v2-0-switchover-qa/

No one will maintain this project? 😢

**Comment by ltparis2018** [comment]
I'm very sorry to say this, but unfortunately we cannot longer maintain the OIL project. Here is the message we set on the OIL main page a few days ago:

"We very much regret that we, the previous OIL development team, are no longer able to support the OIL project with immediate effect. It will not be developed any further by us and we will not provide any bugfixes or security patches from now on. As an open source project it will remain available. If you want to take over the project as a maintainer, please contact oil-support@asideas.de."

Therefore, we, the former maintainers of the project, will not implement the TCF 2.0 standard in OIL. But everyone in the open source community being interested in usage and development of OIL is invited to do the necessary steps.
