### ISSUE TITLE
Switch to TCF v2.0 since TCF v1.1 will soon no longer be supported

### ISSUE THREAD

**Issue by loano** [as-ideas/oil#300]
Currently Oil uses TCF v1.1 which will be no longer supported by end of June.

_TCF 2.0: General Info
 
The „Transparency and Consent Framework” is an industry standard by the IAB Europe to help all parties in adtech to comply with the EU’s GDPR and ePrivacy directive. To allow for planning, the IAB Europe has agreed on the following timeline: 
-	As of 30.04.2020, all adtech parties must support TCF2.0 and all CMP providers should offer a new TCF2.0 compliant CMP 
-	Q2 2020 is the transition phase by the end of which publishers should have a new CMP tested and up and running 
-	As of 30.06.2020 only TCF2 will should be used in the industry across the board 
 
Publishers will not be able to operate with both TCF1.1 and 2.0 simultaneously, as they are not compatible._

More infos and how to implement: [https://iabeurope.eu/tcf-2-0/](https://iabeurope.eu/tcf-2-0/)

**Comment by ltparis2018** [comment]
I'm very sorry to say this, but unfortunately we cannot longer maintain the OIL project. Here is the message we set on the OIL main page a few days ago:

"We very much regret that we, the previous OIL development team, are no longer able to support the OIL project with immediate effect. It will not be developed any further by us and we will not provide any bugfixes or security patches from now on. As an open source project it will remain available. If you want to take over the project as a maintainer, please contact oil-support@asideas.de."

Therefore, we, the former maintainers of the project, will not implement the TCF 2.0 standard in OIL. But everyone in the open source community being interested in usage and development of OIL is invited to do the necessary steps.

**Comment by loano** [comment]
Oh, that's too bad. Unfortunately I can't contribute because I am only an end user. Thank you for the development and the support you have given to this project!

**Comment by Donquiweb** [comment]
It's a pity but RGPD and cookie banner consentement became a complexe framework.
