### ISSUE TITLE
Oil js not working.

### ISSUE THREAD

**Issue by Dhinendran** [as-ideas/oil#306]

**Comment by Dhinendran** [comment]
https://vendorlist.consensu.org/vendorlist.json not working,
unable to accept.
any issue on oiljs api

**Comment by rbuer** [comment]
From https://github.com/as-ideas/oil#project-state : OIL is not TCFv2 compatible and due to that no longer a registered CMP.
We as the former developers do not maintain the Project anymore

**Comment by Dhinendran** [comment]
So it will not work anymor?

**Comment by Ratcreamsoup** [comment]
The switchover deadline for TCF 1.1 has been August 15th. TCF 1.1 operation has been shut down. You will need to migrate to some other CMP solution such as Usercentrics or Sourcepoint or something silimar supporting IAB TCF 2.0. As far as I am aware there is no alternative OpenSource project that provides TCF 2.0 functionality. AS OIL is unfortunately dead as a Dodo.

**Comment by FlxAlbroscheit** [comment]
**facepalm!**

![Es war so klar...](https://i.imgflip.com/4bpupd.jpg)

**Comment by joshfarrant** [comment]
Not sure if this will be useful yet, but just in case anyone does find it useful then I believe this is the last published vendorlist.json.

https://vendorlist.consensu.org/v-215/vendorlist.json

The contents of vendorlist.json, in case the link above no longer works: 
https://gist.github.com/joshfarrant/218a5df4784bf98c5d737860730d63aa

**Comment by Ratcreamsoup** [comment]
Unfortunately the last available vendor list is of no use whatsoever, as any officially registered vendor would have been required to switch over to TCF 2.0 by now. TCF 1.1 is no longer supported as of August 15th. So even if you have AS OIL enabled and point that to a legacy vendor list, the consent information thus compiled would not be relevant to and no longer be processed by any IAB Europe registered ad/analytics vendor. There is really no use at all trying to keep any AD OIL integration working by switching to a legacy vendor list.

**Comment by joshfarrant** [comment]
Makes perfect sense, thank you.
